### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
~~~~~
coqc -Q ../bbv bbv  -R ./src riscv   src/proofs/invert_encode_UJ.v 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
~~~~~

**Comment by samuelgruetter** [comment]
If I remember correctly, `invert_encode_UJ.v` takes about 15min on my machine, and it's just one single tactic invocation, so I guess you'll have to experiment with [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received). Alternatively, if you find a nice spot to put some `idtac` progress output into [`prove_Zeq_bitwise`](https://github.com/mit-plv/riscv-coq/blob/master/src/proofs/prove_Zeq_bitwise.v), I'd be fine with that too (some output which convinces me that it didn't run into an infinite loop is always valuable).

**Comment by samuelgruetter** [comment]
Regarding the error in build https://travis-ci.com/mit-plv/bedrock2-ci/jobs/131167824:

```
File "./src/FlatToRiscv.v", line 1423, characters 8-25:
Error:
Ltac call to "typeclasses eauto (int_or_var_opt)" failed.
Tactic failure: Proof search failed.
```

I'm not surprised this fails with a newer version, and I don't like the code I wrote there. I think `FlatToRiscv.v` should be parameterized over a non-dependent type `mword` rather than using `word wXLEN` everywhere, but I haven't done that refactoring yet...

**Comment by samuelgruetter** [comment]
Good news: First successful build on travis!
Bad news: The build takes about 50min, and 50min is the build timeout too -- that's why some jobs succeed and some fail.

Open questions:
* Can one increase the build timeout?
* Why does one push trigger the same build 4 times?

**Comment by JasonGross** [comment]
> Can one increase the build timeout?

No.  For Coq's Travis ci, you need to shave about 10 minutes off of that, so that they can build Coq, too.  I think there's also a gitlab ci for Coq, which has less stringent build limits

**Comment by JasonGross** [comment]
> Why does one push trigger the same build 4 times?

I don't know where you see 4, but two of them are from "the branch" and "the pull request" (if this PR were a branch on a personal repo without Travis, there wouldn't be a "branch" build)

**Comment by samuelgruetter** [comment]
> I don't know where you see 4, but two of them are from "the branch" and "the pull request" (if this PR were a branch on a personal repo without Travis, there wouldn't be a "branch" build)

Yeah it's just two, got it, thx :+1: 

I got a huge speedup locally by using `rewrite_strat` instead of `rewrite`, but now the build https://travis-ci.com/mit-plv/bedrock2-ci/jobs/131405660 fails with an error I've never seen before:

```
WARNING: The following packages cannot be authenticated!
  coq-theories ocaml-base-nox liblablgtk2-ocaml liblablgtksourceview2-ocaml
  libcoq-ocaml coq coqide
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command "sudo apt-get install $COQ_PACKAGE -y" failed and exited with 100 during .
```

**Comment by JasonGross** [comment]
This is a transient but recurring error in travis.

**Comment by andres-erbsen** [comment]
Following the TODOs on https://github.com/mit-plv/bedrock2/issues/12#issuecomment-399526738:

[x] builds on coq master.
[x] Currently we pass in `EXPECTED_COQC_VERSION="$(coqc --version | sed -n 's/The Coq Proof Assistant, version \([^ ]*\) .*/\1/p')"`, @samuelgruetter if you would like for that to happen in the Makefile instead, feel free to change.
[x] builds without human interaction
[x] builds on travis CI

So I think we are good to go and tell Coq devs to include bedrock2 as a CI development? Thanks for making this work!

**Comment by samuelgruetter** [comment]
We got CI :tada: 

Thanks @andres-erbsen and @JasonGross for your help!

Each job runs in about 20min, so there should be enough time to also build Coq before.

> So I think we are good to go and tell Coq devs to include bedrock2 as a CI development? 

Yes, I think so. @andres-erbsen could you take care of this?

**Pull request merged**
